###################################################################
################## CONFIGURATION FILE FOR TRAUPIXE ################
###################################################################


[GUPIX PATH]
c:\gupixwin\gupix
########### GUPIX-PATH not used on the computer "server-aglae" , default is .\Mydocs\gupixwin ############

[HDF5]
	[analyses_location]
	/
	[analyses_attributes]
	ref object
	start date
	[analyses_dataset-name]
	"x0,x1,x2,x3,x4,x10,x11,x12,x13"
	[dataset_attributes]
	acquisition time
	experiment information
	month
	seconds since midnight
	spectrum sum
	user comment
	year
[\HDF5]
	
[DET0]
X0
[DET1]
X1
[DET2]
X3
[DET3]
X4
[DET4]
X134
[DET5]
X1234
[DET6]
X34
[DET7]
X10
[DET8]
X13
