<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <StartupObject>TRAUPIXE_HDF5.My.MyApplication</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <ImportedNamespaces>PureHDF=False,System.Data=False,System.Drawing=False,System.Windows.Forms=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,TRAUPIXE_HDF5=True</ImportedNamespaces>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <ApplicationIcon>Icone_Traupixe_256.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'" />

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />

  <ItemGroup>
    <Content Include="Icone_Traupixe_256.ico" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="PureHDF" />
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.100.3" />
    <PackageReference Include="PureHDF" Version="1.0.0-alpha.24" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Atomic_mass.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config_Traupixe.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FiTtoPNG_2023_DLL.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="FiTtoPNG_2025_DLL.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Historic_Update.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="NationalInstruments.LabVIEW.Interop.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>